# Generated by Django 2.2.5 on 2022-07-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20220706_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
