# Generated by Django 2.2.5 on 2022-07-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='check_builtin',
            new_name='check_in',
        ),
    ]
